Stdio: Fix linking issues with static libgmp.
Linking of Pike failed with "undefined reference to `__gmpz_import'"
when libgmp was a static library (due to the Gmp module being linked
into the pike binary before the _Stdio module).

This fixes the issue by also linking _Stdio with libgmp.