We're not actually using __func__, and since it's not in our namespace we shouldn't be messing with it anyway. Fixes problem with redefinition of __func__ in <sys/cdefs.h> on FreeBSD.
Rev: src/acconfig.h:1.141