Fixed bug that caused free_all_nodes to free nodes too often. It could be trigged either after compilation errors or when rtldebug is used.
Rev: src/las.c:1.328